site_name: SIIM Hackathon Documentation
repo_url: https://github.com/ImagingInformatics/hackathon-docs/
edit_uri: https://github.com/ImagingInformatics/hackathon-docs/edit/main/
docs_dir: .
theme:
    name: readthedocs
nav: 
    - Getting Started: 
        - Hackathon Event: getting-started/hackathon-event.md
        - Hackathon Server: getting-started/hackathon-server.md
        - ModHeader: getting-started/mod-header.md
        - Slack: getting-started/slack.md
    - What's new:
        - 2025: whats-new/2025.md
        - 2024: whats-new/2024.md
        - 2023: whats-new/2023.md
        - 2022: whats-new/2022.md
        - 2021: whats-new/2021.md
    - APIs:
        - FHIR Intro: apis/fhir-intro.md
        - FHIR-related Technologies: apis/fhircast-and-cds-hooks.md
        - DICOMweb Intro: apis/dicom-web-intro.md
        - DICOMweb STOW: apis/dicom-web-stow.md
        - DICOM to JPG/PNG: apis/dicom-to-jpg-png.md
        - Generative AI: apis/generative-ai.md
        - Ethereum Intro: apis/ethereum-blockchain-intro.md
        - Other APIs/Standards: apis/other-apis-and-standards.md
    - Image Archives:
        - Orthanc: imaging/orthanc.md
        - DCM4CHE: imaging/dcm4che.md
    - Miscellaneous:
        - DICOM Resources: miscellaneous/dicom-resources.md
        - IDE's: miscellaneous/ides.md
        - Docker: miscellaneous/docker.md
        - Data Sets: miscellaneous/data-sets.md
        - Contributing: miscellaneous/contributing.md
plugins:
  - same-dir
